import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/rootLayOut";
const inter = Inter({ subsets: ["latin"] });
import Link from "@/components/Links/link";
import Nav from "@/components/nav"
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,session }) {
  return (
    <html lang="en">
      <head>
        <Link />
      </head>
      <body className={inter.className}>
        <Layout>
          <Nav></Nav>
          {children}
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
