import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/rootLayOut";
const inter = Inter({ subsets: ["latin"] });
import Link from "@/components/Links/link";
import Nav from "@/components/nav"
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,session }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/js/bootstrap.bundle.min.js"></script>

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        ></link>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
      </head>
      <body className={inter.className}>
        <Layout>
          <Nav></Nav>
          {children}
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
