import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/rootLayOut";
const inter = Inter({ subsets: ["latin"] });
import Link from "@/components/Links/link";
import Nav from "@/components/nav"
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,session }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossOrigin="anonymous"
        ></script>
        <script
          src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossOrigin="anonymous"
        ></script>
        <Link />
      </head>
      <body className={inter.className}>
        <Layout>
          <Nav></Nav>
          {children}
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
