// components/RootLayout.js
"use client"
import { Inter } from "next/font/google";
import Nav from "@/components/nav";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,session }) {
  return (  
     <SessionProvider session={session}>
        {children}
     </SessionProvider>
  );
}
